<!--文档-->
      <div class='listcon'>
        <div class='listnrwz'>
          <h1><a href="member/book_request_resp.php?reqid=[field:id/]" class="title">[field:doctitle/]</a></h1>
          <div class='listtips'>
            <ul>
              <li>发布人：[field:uname/]<span>|</span></li>
              <li>悬赏积分：<span style="color:#F00">￥[field:score/]</span><span>|</span></li>
              <li>发布时间：[field:addtime/]<span>|</span></li>
              <li>投稿数：[field:respnum/]</li>
              <!--li>状态：[field:scores/]<span>|</span></li-->
            </ul>
          </div>
        </div>
        <div class='clear'></div>
      </div>
      <!--文档 end-->