<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",43,197);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",282,297);
$z[2]=Array("title","",315,329);
$z[3]=Array("description","",366,386);
$z[4]=Array("writer","",543,558);
$z[5]=Array("stime","",586,600);
$z[6]=Array("filetype","",743,760);
$z[7]=Array("typeurl","",812,828);
$z[8]=Array("typename","",846,863);
$z[9]=Array("click","",910,924);

?>