<dl class="clear">
      <dt class="imgs">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]<!--span class="t">72 Pages</span--></dt>
      <dd class="fc-baidu title"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></dd>
      <dd class="summary">[field:description/]...</dd>
      <dd>
        <ul>
          <!--li class="padding-l"><em title="顶" class="top">顶</em>0<span>|</span></li-->
          <li> 上传人: [field:writer/] </li>
          <li><span>[field:stime/]</span><span>|</span></li>
          <li class="viewhot-tips">热度:<span class='viewhot5'></span><span>|</span></li>
          <li >格式:[field:filetype/]<span>|</span></li>
          <li >分类:<a href="[field:typeurl/]" target="_blank">[field:typename/]</a><span>|</span></li>
          <li >点击:[field:click/]<span>|</span></li>
        </ul>
      </dd>
    </dl>