<div id="UpAuthor" class="g_box">
      <div class="title">文档上传者</div>
      <div class="content">
        <div class="AuthorImg" id="AuthorImg"><a href="[field:spaceurl /]" class="userface"><img src="[field:face/]" width="52" height="52" /></a></div>
        <div class="AuthorInfo" id="AuthorInfo">用户：<a href='[field:spaceurl /]' class="username">[field:uname/]</a><br />
          总文档：[field:totaldocs/]<br />
          <span class='hour'>[field:logintime function="MyDate('Y-m-d H:m',@me)"/]</div>
      </div>
      <div class="tl_b"></div>
      <div class="tr_b"></div>
      <div class="bl_b"></div>
      <div class="br_b"></div>
    </div>