<?php
$z[0]=Array("global","\r\n          \$a=\"\r\n          <li class='r1'><span class='top10'>\";\r\n            \$b=\"</span>\";\r\n            \$c=\"\r\n          <li><span class='top10'>\";\r\n            if (@me % 2 == 1) @me = \$a.@me.\$b;\r\n            else @me = \$c.@me.\$b;\r\n            ",0,302);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("title","",313,327);
$z[2]=Array("arcurl","",335,350);
$z[3]=Array("title","",352,366);

?>