<?php
$z[0]=Array("field","",66,95);
$z[0][4]['name']="typename";
$z[1]=Array("field","",131,159);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n          <li><span class=\"update\">[field:pubdate function=\"GetDateMk(@me)\"/]</span> <a href=\"[field:arcurl/]\" target=\"_blank\" class=\"[field:filetype/]\">[field:title/]</a></li>\r\n          ",265,572);
$z[2][4]['row']="7";
$z[2][4]['titlelen']="32";
$z[2][4]['noflag']="h";
$z[2][4]['imgwidth']="40";
$z[2][4]['imgheight']="50";
$z[2][4]['addfields']="filetype";
$z[2][4]['channelid']="17";

?>