<?php
$z[0]=Array("global","\r\n          \$a=\"\r\n          <li class='r1'><span class='top10'>\";\r\n            \$b=\"</span>\";\r\n            \$c=\"\r\n          <li><span class='top10'>\";\r\n            if (@me % 2 == 1) @me = \$a.@me.\$b;\r\n            else @me = \$c.@me.\$b;\r\n            ",0,302);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("global","",312,346);
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("userid","",368,383);
$z[3]=Array("uname","",417,431);
$z[4]=Array("docnumber","",454,498);
$z[4][4]['function']="null2zero(@me)";
$z[5]=Array("scores","",524,539);

?>