<?php
$z[0]=Array("field","",277,300);
$z[0][4]['name']="id";
$z[1]=Array("global","",767,799);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",979,1011);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1189,1221);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("php","\r\n        if(\$cfg_mb_open=='Y') {\r\n        echo '用户名:\r\n        <input type=\"text\" name=\"username\" size=\"16\" class=\"ipt-txt\" />\r\n        ';\r\n        }\r\n        ",1589,1775);
$z[5]=Array("php","\r\n        if(preg_match(\"/4/\",\$safe_gdopen)){\r\n        echo '验证码:\r\n        <input type=\"text\" name=\"validate\" size=\"4\" class=\"ipt-txt\" style=\"text-transform:uppercase;\"/>\r\n        <img src= \"'.\$cfg_cmspath.'/include/vdimgck.php\" id=\"validateimg\" style=\"cursor:pointer\" onclick=\"this.src=this.src+\\'?\\'\" width=\"60\" height=\"24\"  title=\"点击我更换图片\" alt=\"点击我更换图片\" />';\r\n        }\r\n        ",1785,2222);
$z[6]=Array("php","\r\n      if(\$cfg_mb_open=='Y') {\r\n      echo '\r\n      <script language=\"javascript\" type=\"text/javascript\">CheckCommentLogin();</script>\r\n      ';\r\n      }\r\n      ",2395,2578);
$z[7]=Array("global","",3417,3442);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("global","",3587,3613);
$z[8][4]['name']="cfg_phpurl";
$z[9]=Array("field","",3651,3667);
$z[9][4]['name']="id";
$z[10]=Array("global","",4007,4032);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("global","",4962,4990);
$z[11][4]['name']="cfg_soft_lang";
$z[12]=Array("field","",5056,5072);
$z[12][4]['name']="id";
$z[13]=Array("global","",5415,5440);
$z[13][4]['name']="cfg_phpurl";
$z[14]=Array("global","",5579,5604);
$z[14][4]['name']="cfg_cmsurl";

?>