<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}'><img width='70' height='86' src='{@me['litpic']}'/></a>\"); ",84,245);
$z[0][4]['runphp']="yes";
$z[1]=Array("pagenumber","",286,305);
$z[2]=Array("filetype","",380,397);
$z[3]=Array("arcurl","",470,485);
$z[4]=Array("title","",503,517);
$z[5]=Array("description","",557,577);
$z[6]=Array("click","",831,845);
$z[7]=Array("click","",914,928);
$z[8]=Array("click","",1001,1015);
$z[9]=Array("writer","",1064,1079);

?>