<div class='listcon'>
        <div class='listbook'>
          <div class='imgs'> [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}'><img width='70' height='86' src='{@me['litpic']}'/></a>"); [/field:array] </div>
          <div class='pasefont'>[field:pagenumber/]页</div>
        </div>
        <div class='listicon'><span class="icon [field:filetype/]"></span> </div>
        <div class='listnrwz'>
          <h1><a href='[field:arcurl/]' target='_blank'>[field:title/]</a></h1>
          <div class='lcont'>[field:description/]...</div>
          <div class='listtips'>
            <ul>
              <li><span class="preview"></span>3<span>|</span></li>
              <li><span class="price"></span>￥2.00<span>|</span></li>
              <li><span class="downtimes"></span>[field:click/]<span>|</span></li>
              <li><span class="favtimes"></span>[field:click/]<span>|</span></li>
              <li><span class="commenttimes"></span>[field:click/]<span>|</span></li>
              <li>上传人:[field:writer/]</li>
            </ul>
            <p class='date'>2010-7-24  17:43:0</p>
          </div>
        </div>
        <div class='clear'></div>
      </div>