<?php
$z[0]=Array("item","",4,92);
$z[0][4]['name']="广告管理";
$z[0][4]['link']="ad_main.php";
$z[0][4]['rank']="plus_广告管理";
$z[0][4]['target']="main";
$z[1]=Array("item","",94,196);
$z[1][4]['name']="友情链接";
$z[1][4]['link']="friendlink_main.php";
$z[1][4]['rank']="plus_友情链接模块";
$z[1][4]['target']="main";
$z[2]=Array("item","",198,302);
$z[2][4]['name']="站内新闻发布";
$z[2][4]['link']="mynews_main.php";
$z[2][4]['rank']="plus_站内新闻发布";
$z[2][4]['target']="main";

?>