<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}' width='70' height='86'/></a>\"); ",104,281);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",477,492);
$z[2]=Array("title","",508,522);
$z[3]=Array("description","",562,582);
$z[4]=Array("click","",673,687);
$z[5]=Array("needmoney","",739,757);
$z[6]=Array("click","",806,820);
$z[7]=Array("click","",869,883);
$z[8]=Array("scores","",932,947);
$z[9]=Array("pubdate","",1069,1115);
$z[9][4]['function']="GetDateTimeMK(@me)";

?>