<?php
$z[0]=Array("global","",297,323);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",388,418);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",455,482);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",500,532);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",600,632);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",699,731);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",819,857);
$z[6][4]['filename']="comm_js.htm";
$z[7]=Array("include","",3225,3260);
$z[7][4]['filename']="head.htm";
$z[8]=Array("include","",3311,3352);
$z[8][4]['filename']="top_search.htm";
$z[9]=Array("mynews","\r\n        <li><a href='mynews.php?aid=[field:aid /]'>[field:title /]</a> （发布时间：[field:senddate function=\"GetDateMk(@me)/]，发布人：[field:writer /]）</li>\r\n        ",3578,3810);
$z[9][4]['row']="-1";
$z[9][4]['titlelen']="20";
$z[10]=Array("include","",3957,3994);
$z[10][4]['filename']="footer.htm";

?>